### ISSUE TITLE
integrated study timeline preview

### ISSUE THREAD

**Issue by smeddinck** [MORE-Platform/more-studymanager-frontend#376]
preview of timeline of study events at design time integrated in the MORE study manager frontend in addition to being available in a common calendar format

as a global timeline or based on a “per participant X” or at least “per group Y” level

**Comment by ja-fra** [comment]
We currently provide an iCAL-Export of the Study-Configuration that provides an overview of the scheduled observations and interventions.

As a further enhancement, these schedules shall be rendered in a kind of "Calendar-View" within the study-manager:
* The information to be displayed is aligned with the iCAL-Export.  
* The events shall be filterable by participant and/or study-group.

For now, this view is considered _read-only_. Changing this into an alternative way to also edit the schedules shall be kept in mind when selecting any 3rd-party components.

**Comment by ja-fra** [comment]
Possible library/component for the calendar-view: https://github.com/antoniandre/vue-cal

**Comment by alireza-dhp** [comment]
The study timeline has inconsistencies that need to be addressed.
It has been tested via [study_config_47.json](https://github.com/user-attachments/files/15533091/study_config_47.json) study:

- There is no filter the view by date-range.

- Although limesurvey observation is scheduled to run until the end of the study, and a simple questionnaire observation is defined for 50 days, they do not appear consistently in the calendar.

- The "Relative date" label for the date picker needs to be more descriptive, such as "Relative study start date" or another clearer term.

- The ACC observation displays incorrectly on the calendar: 
(It appears there is a bug in defining an observation which causes this issue.
if an absolute observation is defined without a schedule, and later the schedule date is specified with "multiple observation events," the end date does not update accordingly. Please check the end date for "Accelerometer Mobile Sensor" observation in this study.)

  - It is repeated twice in the weekly/daily view.
![Image](https://github.com/MORE-Platform/more-studymanager-frontend/assets/107924035/1bffa8ca-d5f2-48f7-9cb9-4297164f6614)

  - It appears multiple times in the monthly view.
![Image](https://github.com/MORE-Platform/more-studymanager-frontend/assets/107924035/7eff7030-3240-4956-9be3-6e5a5e9ccf33)

- The hidden/visible icon for interventions is unnecessary since all intervention types are always visible.

- A minor ui/ux issue:
![Image](https://github.com/MORE-Platform/more-studymanager-frontend/assets/107924035/452ac5e4-28f6-4a56-92ba-b4964d7e6020)
