### ISSUE TITLE
Export study calendar link does not work.

### ISSUE THREAD

**Issue by alireza-dhp** [MORE-Platform/more-studymanager-frontend#418]
The URL link for downloading calendar (.ics) file does not work properly.
http://localhost:8085/api/v1/calendar/studies/27/calendar.ics

![image](https://github.com/MORE-Platform/more-studymanager-frontend/assets/107924035/19dd1abe-770c-4845-9682-ace0dff051f0)

**Comment by andresgruber** [comment]
We fixed which prevented the calendar from working. 

But we do not suggest to keep the link to the calendar export because of two major reasons:
1.  The existing export is incomplete because, the calendar of a study might get complex especially if the study has multiple arms, relative observations cannot be simulated on a fixed calendar. Therefore we have built the "live" calendar within the study manager frontend which is directly connected to changes in the study configuration and allows filtering by group, observation, participant and simulating a specific entry date of a participant for a relative study.
2. There is a possible information leak if we continue to use the existing link if one guesses a study id, b/c the link is not secured with authorization.

**Comment by alireza-dhp** [comment]
Thank you for addressing the link issue.
After discussing with our internal team, we agree that removing the link from the study manager dashboard is acceptable for now.
In the future, we would like to request enhancements to the functionality, including implementing proper authorization checks to prevent any potential data leaks.

**Comment by janoliver20** [comment]
https://github.com/MORE-Platform/more-data-gateway/pull/195

**Comment by janoliver20** [comment]
https://github.com/MORE-Platform/more-studymanager-frontend/pull/567

**Comment by andresgruber** [comment]
The link to the calendar has been removed as well as the respective endpoint within the data gateway.
