### ISSUE TITLE
Create Shortcut to duplicate an Integration

### ISSUE THREAD

**Issue by ja-fra** [MORE-Platform/more-studymanager-frontend#420]
Currently, it is not possible to regenerate the secret of an integration.

As a simple workaround, there should be a button to duplicate/clone an integration (using the same name and observation-reference) instead of typing in everything again.

After cloning, the same info-screen like when manually creating an integration is shown to the user.

Additionally, the list of integrations should also show the date when an integration has been created.

**Comment by alireza-dhp** [comment]
It should not be possible to create/clone/delete an integration when the study is not in a (Preview) paused state. This behaviour has appeared after PR #442)

![Image](https://github.com/MORE-Platform/more-studymanager-frontend/assets/107924035/3cda4f5f-223d-4945-9e29-8dc9ced49cd2)

**Comment by benitsch** [comment]
Bug was introduced by PR #445 and will be fixed by PR #450

**Comment by ja-fra** [comment]
@alireza-dhp 
> It should not be possible to create/clone/delete an integration when the study is not in a (Preview) paused state. This behavior has been appeared after PR #442)

From my point of view it **should** be possible to modify (add, remove, delete) the integrations at all times unless the study has been closed:
Changing the integrations does not affect the study-configuration from a participants perspective. It allows to add/change external services sending data while the study is running: Adding an integration is like changing the password.

An integration is always linked to an (existing) observation - and those can only be changed during a "paused"-state.

**Comment by alireza-dhp** [comment]
Thank you for the clarifications @ja-fra . 
If this is implemented for the intended purpose, it should be fine.
Previously, we could only perform CRUD operations for integrations while in the "Pause" state (as same as interventions, ...), so I assumed this was overlooked in the last PR.

**Comment by alireza-dhp** [comment]
There are two issues/enhancements:

1. When adding a new integration while the study is "Active," the Integration title field is read-only. It should be enabled and editable. Please ensure this behavior is applied to all states where integrations are modifiable.
![Image](https://github.com/MORE-Platform/more-studymanager-frontend/assets/107924035/b4fd8af1-ac42-455c-8705-0b21634c38f2)

2. It would be beneficial to edit the Integration title when a user clones the Integration. Currently, the cloned Integration retains the same title, and it cannot be edited afterward since Integrations are not editable.
