### ISSUE TITLE
Relative observation with repeat events

### ISSUE THREAD

**Issue by alireza-dhp** [MORE-Platform/more-studymanager-frontend#549]
Relative observations with repeat events do not show in the mobile app!

Android app version:
4.0.17

Study manager: define an observation:
![image](https://github.com/user-attachments/assets/d2bb05a8-3f6b-4b91-a47e-074cb28b99bb)

mobile app: observation details 
![Screenshot_20241010-103717](https://github.com/user-attachments/assets/23dabfe5-7cc5-4286-a962-0f2bfdbebb3a)

**Comment by alireza-dhp** [comment]
Hi @andresgruber,

I saw that the problem happens when the study's "actual start date" is set after the "planned end date" in the study manager configuration.
In this situation, I believe the user shouldn’t be able to log into the study and should see an error message.

It’s odd that when this happens, the relative observation with repeated events doesn’t show up.
But if the relative observation does not have repeated events, it does appear in the app!

**Comment by janoliver20** [comment]
https://github.com/MORE-Platform/more-data-gateway/pull/188

**Comment by andresgruber** [comment]
Bug fixed for events happening in a study where the study end time has been exceeded.

This fix does not cover the situation where this "I believe the user shouldn’t be able to log into the study and should see an error message" happens, because this was not designed so far. We would need to change the rule, that one can join any "active" study. If such a behavior is needed, we should discuss/design the exact rules and cases.
